services:
  - docker

before_install:
  - docker pull frotty/wurstscript
  - docker run -it -d --name build frotty/wurstscript /bin/sh

install:
  - docker exec build grill update wurstscript
  - docker exec build git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - docker exec build /bin/sh -c "cd $TRAVIS_REPO_SLUG && git checkout -qf $TRAVIS_COMMIT"

script:
  - docker exec -it build /bin/bash
  - cd $TRAVIS_REPO_SLUG
  - grill update
  - grill test
