services:
  - docker

before_install:
  - docker pull frotty/wurstscript
  - docker run -it -d -w $TRAVIS_REPO_SLUG --name build frotty/wurstscript /bin/sh 

install:
  - docker exec build grill update wurstscript
  - docker exec build git clone https://github.com/$TRAVIS_REPO_SLUG.git .
  - docker exec build git checkout -qf $TRAVIS_COMMIT

script:
  - docker exec build grill update
  - docker exec build grill test
