sudo: required
jdk: oraclejdk8

services:
  - docker

before_install:
  - docker pull frotty/wurstscript
  - docker run -d -p 127.0.0.1:80:4567 frotty/wurstscript /bin/sh -c "grill update wurstscript"
  - docker ps -a
  - docker run frotty/wurstscript /bin/sh -c "cd /root/frotty"

install:
  - grill update

script:
  - grill test
